package email

import (
	"mail/pkg/repository/models"
	"time"
)

// FakeEmails presents fake email data for demonstration.
var FakeEmails = map[uint64]*models.Email{
	1: {
		ID:             1,
		Topic:          "Приглашение на мероприятие",
		Text:           "Уважаемый Гость, приглашаем вас на наше предстоящее мероприятие. Будем рады видеть вас в числе участников!",
		PhotoID:        "https://bizprinting.ru/image/catalog/products/full_1913.jpg",
		ReadStatus:     false,
		Flag:           false,
		Deleted:        false,
		DateOfDispatch: time.Date(2023, time.December, 1, 12, 0, 0, 0, time.UTC),
		ReplyToEmailID: 0,
		DraftStatus:    false,
	},
	2: {
		ID:             2,
		Topic:          "Акция: Скидка 50% на новую коллекцию",
		Text:           "Уважаемый клиент, представляем вам нашу новую коллекцию. Только сегодня у вас есть уникальная возможность получить скидку 50% на все товары!",
		PhotoID:        "https://tc-edelweiss.ru/wp-content/uploads/2020/11/zenden-50-discont-new-collection.jpg",
		ReadStatus:     true,
		Flag:           false,
		Deleted:        false,
		DateOfDispatch: time.Date(2024, time.January, 2, 10, 30, 0, 0, time.UTC),
		ReplyToEmailID: 0,
		DraftStatus:    false,
	},
	3: {
		ID:             3,
		Topic:          "Подтверждение заказа",
		Text:           "Ваш заказ №123456 успешно подтвержден. Ожидайте доставку в ближайшие дни. Спасибо за покупку!",
		PhotoID:        "",
		ReadStatus:     true,
		Flag:           false,
		Deleted:        false,
		DateOfDispatch: time.Date(2024, time.January, 5, 15, 0, 0, 0, time.UTC),
		ReplyToEmailID: 0,
		DraftStatus:    false,
	},
	4: {
		ID:             4,
		Topic:          "Поздравляем с днем рождения!",
		Text:           "Дорогой друг, от всей души поздравляем тебя с днем рождения! Пусть этот день будет полон радости и удивительных сюрпризов!",
		PhotoID:        "https://img.redzhina.ru/img/ff/39/ff398e29d9ab85278b84089047722f77.jpg",
		ReadStatus:     false,
		Flag:           false,
		Deleted:        false,
		DateOfDispatch: time.Date(2024, time.January, 27, 8, 0, 0, 0, time.UTC),
		ReplyToEmailID: 0,
		DraftStatus:    false,
	},
	5: {
		ID:             5,
		Topic:          "Новости о продукте",
		Text:           "Мы рады представить вам последние новости о нашем продукте. Новые функции, улучшения и многое другое ждут вас!",
		PhotoID:        "",
		ReadStatus:     true,
		Flag:           false,
		Deleted:        false,
		DateOfDispatch: time.Date(2024, time.February, 5, 14, 45, 0, 0, time.UTC),
		ReplyToEmailID: 0,
		DraftStatus:    false,
	},
	6: {
		ID:             6,
		Topic:          "Важная информация о вашем аккаунте",
		Text:           "Уважаемый пользователь, мы обнаружили необычную активность в вашем аккаунте. Пожалуйста, проверьте вашу учетную запись для дополнительных сведений.",
		PhotoID:        "",
		ReadStatus:     true,
		Flag:           true,
		Deleted:        false,
		DateOfDispatch: time.Date(2024, time.February, 6, 18, 30, 0, 0, time.UTC),
		ReplyToEmailID: 0,
		DraftStatus:    false,
	},
	7: {
		ID:             7,
		Topic:          "Приглашение на вебинар",
		Text:           "Присоединяйтесь к нашему вебинару, который пройдет в следующую среду. Мы обсудим последние тенденции в отрасли и ответим на ваши вопросы.",
		PhotoID:        "",
		ReadStatus:     false,
		Flag:           false,
		Deleted:        false,
		DateOfDispatch: time.Date(2024, time.February, 7, 11, 0, 0, 0, time.UTC),
		ReplyToEmailID: 0,
		DraftStatus:    false,
	},
	8: {
		ID:             8,
		Topic:          "Специальное предложение для постоянных клиентов",
		Text:           "Мы ценим вашу постоянную поддержку. В качестве благодарности предоставляем вам эксклюзивное специальное предложение. Воспользуйтесь им до конца недели!",
		PhotoID:        "https://e-pard.com/assets/img/news/discount_10p_.jpg",
		ReadStatus:     true,
		Flag:           false,
		Deleted:        false,
		DateOfDispatch: time.Date(2024, time.February, 8, 9, 15, 0, 0, time.UTC),
		ReplyToEmailID: 0,
		DraftStatus:    false,
	},
	9: {
		ID:             9,
		Topic:          "Ваш взнос принят",
		Text:           "Благодарим вас за взнос! Ваш вклад помогает нам в достижении наших целей. Будем держать вас в курсе всех событий и новостей.",
		PhotoID:        "",
		ReadStatus:     false,
		Flag:           false,
		Deleted:        false,
		DateOfDispatch: time.Date(2024, time.February, 9, 13, 30, 0, 0, time.UTC),
		ReplyToEmailID: 0,
		DraftStatus:    false,
	},
	10: {
		ID:             10,
		Topic:          "Напоминание о встрече",
		Text:           "Не забудьте о предстоящей встрече в нашем офисе. Мы ждем вас во вторник в 14:00. До скорой встречи!",
		PhotoID:        "",
		ReadStatus:     true,
		Flag:           false,
		Deleted:        false,
		DateOfDispatch: time.Date(2024, time.February, 10, 16, 0, 0, 0, time.UTC),
		ReplyToEmailID: 0,
		DraftStatus:    false,
	},
	11: {
		ID:             11,
		Topic:          "Обновление безопасности",
		Text:           "Мы обновили наши политики безопасности. Пожалуйста, ознакомьтесь с ними и обновите свои настройки для продолжения безопасного использования нашего сервиса.",
		PhotoID:        "",
		ReadStatus:     false,
		Flag:           false,
		Deleted:        true,
		DateOfDispatch: time.Date(2024, time.February, 11, 17, 20, 0, 0, time.UTC),
		ReplyToEmailID: 0,
		DraftStatus:    false,
	},
	12: {
		ID:             12,
		Topic:          "Благодарим за участие в опросе",
		Text:           "Ваше мнение очень важно для нас. Благодарим за участие в нашем последнем опросе. Ваши ответы помогут нам улучшить качество наших услуг.",
		PhotoID:        "",
		ReadStatus:     true,
		Flag:           false,
		Deleted:        false,
		DateOfDispatch: time.Date(2024, time.February, 12, 10, 45, 0, 0, time.UTC),
		ReplyToEmailID: 0,
		DraftStatus:    true,
	},
	13: {
		ID:             13,
		Topic:          "С днем программиста!",
		Text:           "Желаем всем разработчикам безбагового кода, легких решений сложных задач и, конечно же, много вкусного кофе. С праздником, дорогие программисты!",
		PhotoID:        "",
		ReadStatus:     false,
		Flag:           false,
		Deleted:        false,
		DateOfDispatch: time.Date(2024, time.February, 13, 9, 0, 0, 0, time.UTC),
		ReplyToEmailID: 0,
		DraftStatus:    true,
	},
	14: {
		ID:             14,
		Topic:          "Изменение графика работы",
		Text:           "Уважаемые клиенты, обращаем ваше внимание на изменение графика работы нашего офиса в связи с предстоящими праздниками.",
		PhotoID:        "",
		ReadStatus:     true,
		Flag:           false,
		Deleted:        false,
		DateOfDispatch: time.Date(2024, time.February, 14, 11, 30, 0, 0, time.UTC),
		ReplyToEmailID: 0,
		DraftStatus:    false,
	},
	15: {
		ID:             15,
		Topic:          "Приглашаем на открытие нового магазина",
		Text:           "Мы рады пригласить вас на торжественное открытие нашего нового магазина! Ждем вас за эксклюзивными скидками и подарками!",
		PhotoID:        "",
		ReadStatus:     false,
		Flag:           false,
		Deleted:        false,
		DateOfDispatch: time.Date(2024, time.February, 15, 12, 0, 0, 0, time.UTC),
		ReplyToEmailID: 0,
		DraftStatus:    false,
	},
	16: {
		ID:             16,
		Topic:          "Ваше мнение важно для нас!",
		Text:           "Поделитесь своими впечатлениями о нашем продукте. Ваш отзыв поможет нам сделать его еще лучше!",
		PhotoID:        "",
		ReadStatus:     true,
		Flag:           false,
		Deleted:        false,
		DateOfDispatch: time.Date(2024, time.February, 16, 14, 15, 0, 0, time.UTC),
		ReplyToEmailID: 0,
		DraftStatus:    false,
	},
	17: {
		ID:             17,
		Topic:          "Новый курс доступен",
		Text:           "Мы запустили новый курс, который поможет вам повысить ваши профессиональные навыки. Посмотрите программу курса и присоединяйтесь к нам!",
		PhotoID:        "",
		ReadStatus:     false,
		Flag:           true,
		Deleted:        false,
		DateOfDispatch: time.Date(2024, time.February, 17, 16, 45, 0, 0, time.UTC),
		ReplyToEmailID: 0,
		DraftStatus:    false,
	},
}
