// Code generated by MockGen. DO NOT EDIT.
// Source: ./iuser_repo.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	domain_models "mail/internal/microservice/models/domain_models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockUserRepository) Add(user *domain_models.User, ctx context.Context) (*domain_models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", user, ctx)
	ret0, _ := ret[0].(*domain_models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockUserRepositoryMockRecorder) Add(user, ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockUserRepository)(nil).Add), user, ctx)
}

// AddAvatar mocks base method.
func (m *MockUserRepository) AddAvatar(id uint32, fileID, fileType string, ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAvatar", id, fileID, fileType, ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddAvatar indicates an expected call of AddAvatar.
func (mr *MockUserRepositoryMockRecorder) AddAvatar(id, fileID, fileType, ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAvatar", reflect.TypeOf((*MockUserRepository)(nil).AddAvatar), id, fileID, fileType, ctx)
}

// Delete mocks base method.
func (m *MockUserRepository) Delete(id uint32, ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id, ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockUserRepositoryMockRecorder) Delete(id, ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserRepository)(nil).Delete), id, ctx)
}

// DeleteAvatarByUserID mocks base method.
func (m *MockUserRepository) DeleteAvatarByUserID(userID uint32, ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAvatarByUserID", userID, ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAvatarByUserID indicates an expected call of DeleteAvatarByUserID.
func (mr *MockUserRepositoryMockRecorder) DeleteAvatarByUserID(userID, ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAvatarByUserID", reflect.TypeOf((*MockUserRepository)(nil).DeleteAvatarByUserID), userID, ctx)
}

// GetAll mocks base method.
func (m *MockUserRepository) GetAll(offset, limit int, ctx context.Context) ([]*domain_models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", offset, limit, ctx)
	ret0, _ := ret[0].([]*domain_models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockUserRepositoryMockRecorder) GetAll(offset, limit, ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockUserRepository)(nil).GetAll), offset, limit, ctx)
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(id uint32, ctx context.Context) (*domain_models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id, ctx)
	ret0, _ := ret[0].(*domain_models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(id, ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), id, ctx)
}

// GetByOnlyLogin mocks base method.
func (m *MockUserRepository) GetByOnlyLogin(login string, ctx context.Context) (*domain_models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOnlyLogin", login, ctx)
	ret0, _ := ret[0].(*domain_models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOnlyLogin indicates an expected call of GetByOnlyLogin.
func (mr *MockUserRepositoryMockRecorder) GetByOnlyLogin(login, ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOnlyLogin", reflect.TypeOf((*MockUserRepository)(nil).GetByOnlyLogin), login, ctx)
}

// GetByVKID mocks base method.
func (m *MockUserRepository) GetByVKID(vkId uint32, ctx context.Context) (*domain_models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByVKID", vkId, ctx)
	ret0, _ := ret[0].(*domain_models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByVKID indicates an expected call of GetByVKID.
func (mr *MockUserRepositoryMockRecorder) GetByVKID(vkId, ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByVKID", reflect.TypeOf((*MockUserRepository)(nil).GetByVKID), vkId, ctx)
}

// GetUserByLogin mocks base method.
func (m *MockUserRepository) GetUserByLogin(login, password string, ctx context.Context) (*domain_models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByLogin", login, password, ctx)
	ret0, _ := ret[0].(*domain_models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByLogin indicates an expected call of GetUserByLogin.
func (mr *MockUserRepositoryMockRecorder) GetUserByLogin(login, password, ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByLogin", reflect.TypeOf((*MockUserRepository)(nil).GetUserByLogin), login, password, ctx)
}

// InitAvatar mocks base method.
func (m *MockUserRepository) InitAvatar(id uint32, fileID, fileType string, ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitAvatar", id, fileID, fileType, ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitAvatar indicates an expected call of InitAvatar.
func (mr *MockUserRepositoryMockRecorder) InitAvatar(id, fileID, fileType, ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitAvatar", reflect.TypeOf((*MockUserRepository)(nil).InitAvatar), id, fileID, fileType, ctx)
}

// Update mocks base method.
func (m *MockUserRepository) Update(newUser *domain_models.User, ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", newUser, ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUserRepositoryMockRecorder) Update(newUser, ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepository)(nil).Update), newUser, ctx)
}
