// Code generated by MockGen. DO NOT EDIT.
// Source: iemail_service.go

// Package mock is a generated GoMock package.
package mock

import (
	models "mail/pkg/domain/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEmailUseCase is a mock of EmailUseCase interface.
type MockEmailUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockEmailUseCaseMockRecorder
}

// MockEmailUseCaseMockRecorder is the mock recorder for MockEmailUseCase.
type MockEmailUseCaseMockRecorder struct {
	mock *MockEmailUseCase
}

// NewMockEmailUseCase creates a new mock instance.
func NewMockEmailUseCase(ctrl *gomock.Controller) *MockEmailUseCase {
	mock := &MockEmailUseCase{ctrl: ctrl}
	mock.recorder = &MockEmailUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailUseCase) EXPECT() *MockEmailUseCaseMockRecorder {
	return m.recorder
}

// CheckRecipientEmail mocks base method.
func (m *MockEmailUseCase) CheckRecipientEmail(recipient, requestID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckRecipientEmail", recipient, requestID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckRecipientEmail indicates an expected call of CheckRecipientEmail.
func (mr *MockEmailUseCaseMockRecorder) CheckRecipientEmail(recipient, requestID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckRecipientEmail", reflect.TypeOf((*MockEmailUseCase)(nil).CheckRecipientEmail), recipient, requestID)
}

// CreateEmail mocks base method.
func (m *MockEmailUseCase) CreateEmail(newEmail *models.Email, requestID string) (int64, *models.Email, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmail", newEmail, requestID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(*models.Email)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateEmail indicates an expected call of CreateEmail.
func (mr *MockEmailUseCaseMockRecorder) CreateEmail(newEmail, requestID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmail", reflect.TypeOf((*MockEmailUseCase)(nil).CreateEmail), newEmail, requestID)
}

// CreateProfileEmail mocks base method.
func (m *MockEmailUseCase) CreateProfileEmail(email_id int64, sender, recipient, requestID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProfileEmail", email_id, sender, recipient, requestID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProfileEmail indicates an expected call of CreateProfileEmail.
func (mr *MockEmailUseCaseMockRecorder) CreateProfileEmail(email_id, sender, recipient, requestID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProfileEmail", reflect.TypeOf((*MockEmailUseCase)(nil).CreateProfileEmail), email_id, sender, recipient, requestID)
}

// DeleteEmail mocks base method.
func (m *MockEmailUseCase) DeleteEmail(id uint64, login, requestID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEmail", id, login, requestID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteEmail indicates an expected call of DeleteEmail.
func (mr *MockEmailUseCaseMockRecorder) DeleteEmail(id, login, requestID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEmail", reflect.TypeOf((*MockEmailUseCase)(nil).DeleteEmail), id, login, requestID)
}

// GetAllEmailsIncoming mocks base method.
func (m *MockEmailUseCase) GetAllEmailsIncoming(login, requestID string, offset, limit int) ([]*models.Email, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllEmailsIncoming", login, requestID, offset, limit)
	ret0, _ := ret[0].([]*models.Email)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllEmailsIncoming indicates an expected call of GetAllEmailsIncoming.
func (mr *MockEmailUseCaseMockRecorder) GetAllEmailsIncoming(login, requestID, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllEmailsIncoming", reflect.TypeOf((*MockEmailUseCase)(nil).GetAllEmailsIncoming), login, requestID, offset, limit)
}

// GetAllEmailsSent mocks base method.
func (m *MockEmailUseCase) GetAllEmailsSent(login, requestID string, offset, limit int) ([]*models.Email, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllEmailsSent", login, requestID, offset, limit)
	ret0, _ := ret[0].([]*models.Email)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllEmailsSent indicates an expected call of GetAllEmailsSent.
func (mr *MockEmailUseCaseMockRecorder) GetAllEmailsSent(login, requestID, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllEmailsSent", reflect.TypeOf((*MockEmailUseCase)(nil).GetAllEmailsSent), login, requestID, offset, limit)
}

// GetEmailByID mocks base method.
func (m *MockEmailUseCase) GetEmailByID(id uint64, login, requestID string) (*models.Email, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailByID", id, login, requestID)
	ret0, _ := ret[0].(*models.Email)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailByID indicates an expected call of GetEmailByID.
func (mr *MockEmailUseCaseMockRecorder) GetEmailByID(id, login, requestID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailByID", reflect.TypeOf((*MockEmailUseCase)(nil).GetEmailByID), id, login, requestID)
}

// UpdateEmail mocks base method.
func (m *MockEmailUseCase) UpdateEmail(updatedEmail *models.Email, requestID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmail", updatedEmail, requestID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEmail indicates an expected call of UpdateEmail.
func (mr *MockEmailUseCaseMockRecorder) UpdateEmail(updatedEmail, requestID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmail", reflect.TypeOf((*MockEmailUseCase)(nil).UpdateEmail), updatedEmail, requestID)
}
