global:
  scrape_interval: 30s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8080']

  - job_name: 'auth'
    static_configs:
      - targets: ['auth:9094']

  - job_name: 'email'
    static_configs:
      - targets: ['email:9092']

  - job_name: 'session'
    static_configs:
      - targets: ['session:9093']

  - job_name: 'user'
    static_configs:
      - targets: ['user:9091']

  - job_name: 'folder'
    static_configs:
      - targets: ['folder:9095']

  - job_name: 'questionnaire'
    static_configs:
      - targets: ['questionnaire:9096']

  - job_name: 'node exporter'
    static_configs:
      - targets: ['node-exporter:9100']