name: CHECK

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  tests:
    name: Tests check
    runs-on: ubuntu-latest
    steps:
      - name: Installation Go v1.22
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.x'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Start tests
        run: |
          go get github.com/golang/mock/gomock
          go install github.com/golang/mock/mockgen
          go get golang.org/x/tools/go/packages
          make mock
          make tests

  linter:
    name: Linter check
    runs-on: ubuntu-latest
    steps:
      - name: Installation Go v1.22
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.x'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run linter
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
          $(go env GOPATH)/bin/golangci-lint run --timeout=5m --disable=staticcheck,gosimple